# Site settings
title: James Winegar's blog
email: jameswine@gmail.com
description: Musings about things I find interesting
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://jameswinegar.github.io" # the base hostname & protocol for your site
twitter_username: James_Wine
github_username:  jameswinegar

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
theme: jekyll-theme-slate
